### ISSUE TITLE
clear stack on re selecting menu option 

### ISSUE THREAD

**Issue by rizwan321** [smihajlovski/instagram-like-backstack#1]
Hello,

first of all you have done awesome work. 

i want to use your library and find it very useful.

i need one modification as in Instagram 

when user opens application and landed to Main home tab here user select option and go to home subpage1 and again select option from here and go to home subpage2 

now if user re select home tab again user should landed to MainHome tab and subpage1 and subpage2 should automatically remove from fragment stack

waiting for your kind response

thanks

**Comment by smihajlovski** [comment]
Hey @rizwan321 ,

Thanks for the kind words and sorry for my late response.

Basically, when the user clicks for example `Home` twice, should be navigated to the starting screen of `Home`, correct?

I was thinking on implementing this functionality as well, but haven't had the time. I'll do it really soon, but this is pretty trivial, you can probably do it yourself. In any case I will address this issue when I implement it.

Regards,
Stefan

**Comment by rizwan321** [comment]
@smihajlovski thank you for your assistance.

i have done it myself.

i just replace Bottom Navigation Menu with TabLayout which helps us to detect that user reselected the tab

in the method on onTabReselected of TabLayout.addOnTabSelectedListener i just added below lines



> // if user reselect tab then clear all fragments and pop last fragment on top
>         while (stacks.get(currentTab).size() > 1) {
>             stacks.get(currentTab).pop();
>         }
> 
>         Fragment fragment = stacks.get(currentTab).elementAt(stacks.get(currentTab).size() - 1);
>         removeFragment(getSupportFragmentManager(), fragment, currentFragment);
>         assignCurrentFragment(fragment);

**Comment by smihajlovski** [comment]
This has been now implemented in cff1de992ad9fc8e92717e38ffa588e3ffff9128 commit.
