### ISSUE TITLE
always retain the first position selected tab

### ISSUE THREAD

**Issue by mochadwi** [smihajlovski/instagram-like-backstack#2]
Hello, Stefan Mihajlovski looks like the first selected fragment will be removed and when onBackPressed take places, it stops on the second fragment selected. Is this the right behaviour? I think it should be back to the first selected fragment (which is TAB_HOME) even the user has navigated to the home.

E.g: 
1. HOME selected
2. DASHBOARD selected
3. HOME selected again
4. NOTIFICATION selected

`user using onBackPressed. Should be: NOTIFICATION -> HOME -> DASHBOARD -> and HOME -> then exits.`

But, your code stops on the dashboard instead.

`NOTIFICATION -> HOME -> DASHBOARD -> then exits.`

I've also commented out this on your medium article. Thank you very much for the hard work you spent on this awesome library :)

**Comment by smihajlovski** [comment]
Hey @mochadwi thanks for the kind words and I'm glad you like it!
Regarding your question, that is the intended behavior, as this is how the navigation on `Instagram` looks as well.

**Comment by mochadwi** [comment]
I've made a PR for this issue and hopefully, this will be good enough for those wants to go back and reset to the home tab. #3
